// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// UsersRequestDelete defines model for UsersRequestDelete.
type UsersRequestDelete struct {
	ID int `json:"ID"`
}

// UsersRequestGet defines model for UsersRequestGet.
type UsersRequestGet = map[string]interface{}

// UsersRequestPost defines model for UsersRequestPost.
type UsersRequestPost struct {
	Name string `json:"Name"`
}

// UsersRequestPut defines model for UsersRequestPut.
type UsersRequestPut struct {
	ID   int    `json:"ID"`
	Name string `json:"Name"`
}

// UsersResponseDelete defines model for UsersResponseDelete.
type UsersResponseDelete struct {
	Users *[]struct {
		ID   *int    `json:"ID,omitempty"`
		Name *string `json:"Name,omitempty"`
	} `json:"users,omitempty"`
}

// UsersResponseGet defines model for UsersResponseGet.
type UsersResponseGet struct {
	Users *[]struct {
		ID   *int    `json:"ID,omitempty"`
		Name *string `json:"Name,omitempty"`
	} `json:"users,omitempty"`
}

// UsersResponsePost defines model for UsersResponsePost.
type UsersResponsePost struct {
	Users *[]struct {
		ID   *int    `json:"ID,omitempty"`
		Name *string `json:"Name,omitempty"`
	} `json:"users,omitempty"`
}

// UsersResponsePut defines model for UsersResponsePut.
type UsersResponsePut struct {
	Users *[]struct {
		ID   *int    `json:"ID,omitempty"`
		Name *string `json:"Name,omitempty"`
	} `json:"users,omitempty"`
}

// DeleteUsersJSONRequestBody defines body for DeleteUsers for application/json ContentType.
type DeleteUsersJSONRequestBody = UsersRequestDelete

// GetUsersJSONRequestBody defines body for GetUsers for application/json ContentType.
type GetUsersJSONRequestBody = UsersRequestGet

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UsersRequestPost

// PutUsersJSONRequestBody defines body for PutUsers for application/json ContentType.
type PutUsersJSONRequestBody = UsersRequestPut

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ユーザ削除
	// (DELETE /users)
	DeleteUsers(ctx echo.Context) error
	// ユーザ一覧取得
	// (GET /users)
	GetUsers(ctx echo.Context) error
	// ユーザ登録
	// (POST /users)
	PostUsers(ctx echo.Context) error
	// ユーザ更新
	// (PUT /users)
	PutUsers(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteUsers converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUsers(ctx)
	return err
}

// GetUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsers(ctx)
	return err
}

// PostUsers converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsers(ctx)
	return err
}

// PutUsers converts echo context to params.
func (w *ServerInterfaceWrapper) PutUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutUsers(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(baseURL+"/users", wrapper.DeleteUsers)
	router.GET(baseURL+"/users", wrapper.GetUsers)
	router.POST(baseURL+"/users", wrapper.PostUsers)
	router.PUT(baseURL+"/users", wrapper.PutUsers)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9SVz2sTQRTH/5Xw9Lgkq/W0NyVSFkFDwZN4GHdf0inZmXF+FENZsM1FRfBWKRW8SFXw",
	"ICIiWvxnton2v5CZjZts3ZBCS35cwvDy5r3PzPfNd3cg4ongDJlWEOyAijYxIW55W0ouN1AJzhTagJBc",
	"oNQU3d8Rj10Un5BEdBGCG77vge4JhAAo09hBCakHCSpFOuVUCNk26dK4JvGxQaVrgkiSoEapoKihtKSs",
	"A2nqgU2jEmMIHuR9x2UfFvn80RZG2ra8r1Cqjbx0E7uoK/DDpv09i3umV9icWX8d9USh6pwWV/p/grsk",
	"wYmtU47rsmZBtIw+7wm9c/YNm+DNbJ7PxrQrNjbJLqjGRF0cMC1AiJSkBxOBKWQjcZYNq3oeloDLLAeW",
	"DVHW5m471c4xHGjtZisED7ZRKsoZBHCt7td9240LZERQCGCt7tfXwANB9KYDbBQniItBtQcgmnIWxhBA",
	"PsCuA+SvAJW+xeNe7nNMI3MXQ4To0sjta2wpC/DPMO3qqsQ2BHClMXbUxshOGxWOlJZfnJYGXSCXwvFe",
	"9/3LJii9WIcQo4okFTq/0Ht3wMXaxHT1pTUvf0oq2p78eDZ88zbbPcx2P2V7H7L+x6x/7EZDmSQhsgcB",
	"ZP2jrH+c7X0bPH9xevDOcnby911Wcx31vKS0/rJIHYv+qyfiyfenf47eD17tD369trRi5IllLa1TzktM",
	"58qLVHMMsHpy/j74efryixPSVOlo5iejWbCKZmVFHB5+He5/tmXSvwEAAP//JYXWJRgMAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
