FROM mysql:8.0

# タイムゾーンを日本時間に設定
ENV TZ=Asia/Tokyo

ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=app_db
ENV MYSQL_USER=app_user
ENV MYSQL_PASSWORD=app_password

COPY ./my.cnf /etc/mysql/conf.d/my.cnf
COPY ./initdb/*.sql /docker-entrypoint-initdb.d/

#CMD ["mysqld","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]

EXPOSE 3306
